### ISSUE TITLE
推理

### ISSUE THREAD

**Issue by cutterpoint** [dusens/llama-3-8B-Instruct-text2sql#1]
你好这个应该怎么用呢，我本地跑起来各种报错

RuntimeError: shape '[1, 40, 32, 128]' is invalid for input of size 40960

![image](https://github.com/dusens/llama-3-8B-Instruct-text2sql/assets/13513551/ca182596-776a-47b0-8461-8ae9e7067efd)

**Comment by cutterpoint** [comment]
可以了，torch版本用错了。。。。 2.0以上才行

**Comment by zhangsone** [comment]
> 你好这个应该怎么用呢，我本地跑起来各种报错
> 
> RuntimeError: shape '[1, 40, 32, 128]' is invalid for input of size 40960
> 
> ![image](https://private-user-images.githubusercontent.com/13513551/333474059-ca182596-776a-47b0-8461-8ae9e7067efd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjA5MTgsIm5iZiI6MTcyMTk2MDYxOCwicGF0aCI6Ii8xMzUxMzU1MS8zMzM0NzQwNTktY2ExODI1OTYtNzc2YS00N2IwLTg0NjEtOGFlOWU3MDY3ZWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAyMjMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMzQwNDQyNGVmNmE2MGNmNWJlNGMwMGU0MDBkYmQ2MGRhNWQ1ZDVhNmY1MTZiODA3YjI1YTY4MjIzNzM0YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i8rhiKVfrm4MF_JzyABnFtBsqu2kqBS4NortlwTzxn0)

你好，请问你这个模型是怎么加载起来的，里面没有配置文件啊
